from django.db import connection
from django.http import HttpResponse


def fix_db(request):
    with connection.cursor() as cursor:
        # Manually create the table and the row
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS django_site (
                id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                domain varchar(100) NOT NULL,
                name varchar(50) NOT NULL
            );
            INSERT INTO django_site (domain, name) 
            VALUES ('diary-app-mvp2.onrender.com', 'Diary App')
            ON CONFLICT DO NOTHING;
        """)
    return HttpResponse("Database Table Created Successfully!")
